export const ERROR_CODES = [
	'INVALID_INPUT',
	'NOT_FOUND',
	'ALREADY_INITIALIZED',
	'SCHEMA_TOO_NEW',
	'NO_DATABASE_OPEN',
	'UNKNOWN_METHOD',
	'STORAGE_UNAVAILABLE',
	'ACCOUNT_CLOSED',
	'ACCOUNT_HAS_TRANSACTIONS',
	'ACCOUNT_BALANCE_NOT_ZERO',
	'CATEGORY_REQUIRED',
	'CATEGORY_NOT_ALLOWED',
	'SYSTEM_ENTITY_READONLY',
	'GROUP_NOT_EMPTY',
	'REASSIGN_REQUIRED',
	'SPLIT_TOO_FEW_LINES',
	'SPLIT_SUM_MISMATCH',
	'TRANSFER_INVALID',
	'PAYEE_EXISTS',
	'PAYEE_IN_USE',
	'SCHEDULE_STALE',
	'SCHEDULE_ENDED',
	'BACKUP_NOT_RECOGNIZED',
	'BACKUP_DAMAGED',
	'BACKUP_NOT_MONETA',
	'BACKUP_TOO_NEW',
	'BACKUP_ENCRYPTED',
	'BACKUP_WRONG_KEY',
	'BACKUP_KEYS_UNAVAILABLE',
	'RESTORE_PARTIAL',
	'CURRENCY_LOCKED',
	'CLOUD_AUTH_NEEDED',
	'CLOUD_PERMISSION_DENIED',
	'CLOUD_POPUP_BLOCKED',
	'CLOUD_UNAVAILABLE',
	'CLOUD_STORAGE_FULL',
	'CLOUD_NOT_ENCRYPTED',
	'CLOUD_FAILED',
	'WORKER_FAILED',
	'INTERNAL'
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export class DomainError extends Error {
	constructor(
		public readonly code: ErrorCode,
		message: string = code,
		public readonly details?: unknown
	) {
		super(message);
		this.name = 'DomainError';
	}
}
