// Writes the emoji picker's data from Emojibase (`pnpm emoji`): every fully qualified emoji in
// Unicode's order, except the components (skin tones and hair on their own), with only what the
// picker uses. Run it again after updating `emojibase-data`.
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { join } from 'node:path';
import { applyTone, SKIN_TONES } from './skin-tone.ts';

const here = import.meta.dirname;
const require = createRequire(import.meta.url);

interface Emoji {
	label: string;
	hexcode: string;
	emoji: string;
	tags?: string[];
	group?: number;
	version: number;
	tone?: number | number[];
	skins?: Emoji[];
}

/** Emojibase's groups (`meta/groups.json`) in the picker's: people go with the smileys. */
const GROUPS: Record<number, string> = {
	0: 'smileys',
	1: 'smileys',
	3: 'animals',
	4: 'food',
	5: 'travel',
	6: 'activities',
	7: 'objects',
	8: 'symbols',
	9: 'flags'
};
const ORDER = ['smileys', 'animals', 'food', 'activities', 'travel', 'objects', 'symbols', 'flags'];

/** Emojibase's locale for each of the app's. */
const LOCALES: Record<string, string> = { en: 'en', 'pt-BR': 'pt' };

async function load(locale: string): Promise<Emoji[]> {
	const file = require.resolve(`emojibase-data/${locale}/data.json`);
	return JSON.parse(await readFile(file, 'utf8')) as Emoji[];
}

const { version: emojibaseVersion } = JSON.parse(
	await readFile(require.resolve('emojibase-data/package.json'), 'utf8')
) as { version: string };

const all = (await load('en')).filter((e) => e.group !== undefined && e.group in GROUPS);
const emojis = ORDER.flatMap((id) => all.filter((e) => GROUPS[e.group!] === id));

/** The sequence with the same skin tone on every person, or undefined when Emojibase has none. */
function uniformSkin(emoji: Emoji, tone: number): string | undefined {
	return emoji.skins?.find((s) =>
		Array.isArray(s.tone) ? s.tone.every((t) => t === tone) : s.tone === tone
	)?.emoji;
}

// `applyTone` covers every emoji but a few; those carry their toned forms in the data.
const toneExceptions: Record<string, string[]> = {};
for (const emoji of emojis) {
	if (!emoji.skins) continue;
	const toned = SKIN_TONES.map((_, i) => uniformSkin(emoji, i + 1));
	if (toned.some((t) => t === undefined))
		throw new Error(`No uniform skin tone for ${emoji.label}`);
	if (toned.some((t, i) => t !== applyTone(emoji.emoji, i + 1)))
		toneExceptions[emoji.emoji] = toned as string[];
}

/** The first emoji of each version, to tell which ones the device can show. */
const samples = new Map<number, string>();
for (const emoji of [...emojis].sort((a, b) => a.version - b.version)) {
	const current = samples.get(emoji.version);
	// A single code point shows best whether it is missing: a box rather than two emoji.
	if (current === undefined || ([...current].length > 1 && [...emoji.emoji].length === 1))
		samples.set(emoji.version, emoji.emoji);
}

const header = `// Generated by generate.ts from emojibase-data ${emojibaseVersion} (\`pnpm emoji\`). Do not edit.\n`;

const groups = ORDER.map((id) => {
	const entries = emojis
		.filter((e) => GROUPS[e.group!] === id)
		.map((e) => `[${JSON.stringify(e.emoji)},${e.version}${e.skins ? ',1' : ''}]`);
	return `\t{ id: '${id}', emojis: [${entries.join(',')}] }`;
});

await writeFile(
	join(here, 'emoji-data.ts'),
	`${header}import type { EmojiGroupData } from './emoji';

/** Every emoji by group, in Unicode's order: [emoji, Emoji version, 1 when it takes a skin tone]. */
export const EMOJI_GROUPS: readonly EmojiGroupData[] = [
${groups.join(',\n')}
];

/** The toned forms (light to dark) of the emoji that \`applyTone\` gets wrong. */
export const TONE_EXCEPTIONS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(toneExceptions)};

/** One emoji of each Emoji version, to test whether the device can show that version. */
export const VERSION_SAMPLES: readonly (readonly [number, string])[] = ${JSON.stringify([...samples])};
`
);

// Names and keywords, one line per emoji in the order above: "name\\tkeyword keyword".
for (const [appLocale, locale] of Object.entries(LOCALES)) {
	const byHex = new Map((await load(locale)).map((e) => [e.hexcode, e]));
	const lines = emojis.map((e) => {
		const named = byHex.get(e.hexcode) ?? e;
		const tags = (named.tags ?? []).filter((t) => !named.label.includes(t));
		return `${named.label}\t${tags.join(' ')}`.replace(/\s+$/, '');
	});
	await writeFile(
		join(here, 'names', `${appLocale}.ts`),
		`${header}/** Each emoji's name and keywords, one line each: "name\\tkeyword keyword". */\nexport default ${JSON.stringify(lines.join('\n'))};\n`
	);
}

console.log(`${emojis.length} emoji, ${Object.keys(toneExceptions).length} tone exceptions`);
